# Fichier : .github/workflows/docker-ci.yml
name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write # Pour pousser l'image vers le GitHub Container Registry

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-and-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
